# --- Stage 1: Build aplication ---
    FROM node:20-alpine AS build

    # Tetapkan direktori kerja
    WORKDIR /app
    
    # Salin package.json dan package-lock.json
    COPY package*.json ./
    
    # Instal dependensi
    RUN npm install
    
    # Salin sisa kode aplikasi
    COPY . .
    
    # Build aplikasi untuk production
    RUN npm run build
    
    # --- Stage 2: Serve aplication with Nginx ---
    FROM nginx:stable-alpine
    
    # Salin hasil build dari stage sebelumnya ke direktori default Nginx
    COPY --from=build /app/dist /usr/share/nginx/html
    
    # Ekspos port 80 untuk Nginx
    EXPOSE 80
    
    # Perintah untuk menjalankan Nginx
    CMD ["nginx", "-g", "daemon off;"]